version: '1.0.0'

services:
  api:
    container_name: reunion-social-media-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000:8000
    depends_on:
      - "database"
    env_file: '.env'
    restart: always
    command: mocha --serial test/appTest.js
