version: '3.9'

services:
  api:
    container_name: reunion-social-media-api
    build: ./
    ports:
      - 3000:8000
    depends_on:
      - "database"
    env_file: '.env'
    restart: always
    command: sh -c "npm run db-migrate && npm run start"